name: clang-format

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 10
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang-format Robot
        author_email: timi.makkonen@gmail.com
        message: 'Format code using ''clang-format'''
      env:
        GITHUB_TOKEN: ${{ secrets.MY_REPO_ACCESS_TOKEN }}